import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    // backgroundColor: "#191712",
    alignItems: "center",
    justifyContent: "center",
  },
  // wrapper: {
  //   flex: 1,
  //   justifyContent: "center",
  //   alignItems: "center",
  //   padding: 20,
  // },
  title: {
    marginBottom: 20,
    fontSize: 24,
    color: "#FFEBB8",
  },
  create: {
    top: 150,
    // position: "absolute",
  },
  // input: {
  //   height: 50,
  //   width: "80%",
  //   marginVertical: 10,
  //   borderWidth: 1,
  //   borderColor: "#FFEBB8",
  //   borderRadius: 10,
  //   paddingLeft: 15,
  //   color: "#FFEBB8",
  // },
  input: {
    top: 20,
    paddingLeft: 10,
    height: 40,
    margin: 12,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: "#FFEBB8",
    color: "#FFEBB8",
  },
  scrollContainer: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    height: 700,
  },
  card: {
    backgroundColor: "#4C4637",
    width: 300,
    height: 450,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#FFEBB8",
    // top: 200,
    // position: "absolute",
  },
  button: {
    backgroundColor: "#FFEBB8",
    // color: "#4C4637",
    // color: "white",
    width: 300,
    height: 150,
    top: -1,
    left: -1,
    // top: 200,
    position: "absolute",
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
  // button: {
  //   marginTop: 20,
  //   backgroundColor: "#FFEBB8",
  //   paddingVertical: 10,
  //   paddingHorizontal: 20,
  //   borderRadius: 10,
  //   elevation: 2,
  // },
  // smallerButton: {
  //   backgroundColor: "#FFEBB8",
  //   margin: 12,
  //   height: 40,
  //   // width: 280,
  //   top: 20,
  //   // textAlign: "center",
  //   borderRadius: 10,
  //   alignItems: "center",
  //   justifyContent: "center",
  //   // bottom: 0,
  // },
  smallerButton: {
    backgroundColor: "#FFEBB8",
    margin: 12,
    height: 40,
    // width: 280,
    top: 20,
    // textAlign: "center",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  createAccount: {
    // left: 10,
    top: 10,
    color: "#FFEBB8",
    fontSize: 20,
    textAlign: "center",
    // position: "absolute",
  },
  text: {
    color: "#4C4637",
    fontSize: 20,
    textAlign: "center",
  },
  message: {
    padding: 15,
    color: "white",
  },
});
export default styles;
