import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    page:{
        justifyContent: 'center',
        padding: 10,
        // borderColor: 'red',
        // borderWidth: 1,
        // width: 100,
        // height: 100,
    },
    title: {
        color: "#FFEBB8",
        fontSize: 25,
        // top: -150,
        // position: "absolute",
        textAlign: "center",
        marginBottom: 50,
        padding: 10,
        position: "fixed",
      },
    ayah: {
        fontSize: 25,
        // flexWrap: "wrap",
        // justifyContent: "right",
        // flexDirection: "row-reverse",
        // paddingtop: 10,
    },
    scrolly: {
        // height: 300, 
        // top: -50,
        // justifyContent: 'center',
        flexDirection: 'row-reverse',
        flexWrap: 'wrap',

      },
    container: {
        // flex: 1,
        // backgroundColor: '#191712',
        // alignItems: 'center',
        // width: '30',
        // height: '500',
        // marginTop: 50,
        // marginBottom: 50,
        // fontSize: 20,
        // marginLeft: 100,
        borderColor: '#FFEBB8',
        padding: 10,
        borderRadius: 10,
        borderWidth: 1,
        // flexDirection: 'row'
        // position: 'absolute',
        // alignContent: 'center',
        // justifyContent: 'center',
      },
    button: {
        borderRadius: 50,
        color: '#FFEBB8',
        // borderColor: 'red',
        // borderWidth: 1,
        height: 120,
        width: 120,
        shadowRadius: 30,
        shadowOpacity: 1,
        justifyContent: "center",
        alignItems: "center",
        opacity: 1,
        bottom: -100,
        shadowColor: "#FFEBB8",
        zIndex: 1,
        right: -250,
        // position: 'absolute',
      },
    });
    export default styles;