import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    // flex: 1,
    backgroundColor: "#191712",
    // backgroundColor: "#4C4637",
    alignItems: "center",
    justifyContent: "center",
    // top: 60,
    // height: 700,
    // width: 400,
    // borderColor: "#FFEBB8",
    // borderWidth: 1,
  },
  title: {
    color: "#FFEBB8",
    fontSize: 30,
    top: -40,
    // position: "absolute",
    textAlign: "left",
  },
  button: {
    backgroundColor: "#4C4637",
    margin: 12,
    width: 230,
    height: 40,
    borderRadius: 10,
    borderColor: "#FFEBB8",
    justifyContent: "center",
    // alignItems: "center",
    paddingLeft: 40,
    zIndex: 1,
  },
  text: {
    color: "#FFEBB8",
    fontSize: 20,
  },
  index: {
    textAlign: "left",
    color: "#FFEBB8",
    fontSize: 20,
    margin: 12,
    paddingTop: 10,
    // width: 250,
    height: 40,
    // borderWidth: 1,
    // borderColor: "#FFEBB8",
    justifyContent: "center",
    alignItems: "center",
  },
  surahContainer: {
    flexDirection: "row",
    borderColor: "#FFEBB8",
    // borderWidth: 1,
    paddingRight: 30,
  },
  //   surahCompunent: {
  //     color: "#FFEBB8",
  //     fontSize: 20,
  //     margin: 12,
  //     paddingTop: 10,
  //     // width: 250,
  //     height: 40,
  //     // borderWidth: 1,
  //     // borderColor: "#FFEBB8",
  //     justifyContent: "center",
  //     alignItems: "center",
  //   },
});
export default styles;
